### ISSUE TITLE
dependancy missing ?

### ISSUE THREAD

**Issue by tiger-seo** [toabctl/jiracli#24] opened 2016-01-22 18:19 UTC
```
D:\>jiracli -h
Traceback (most recent call last):
  File "D:\server\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\server\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\server\python34\Scripts\jiracli.EXE\__main__.py", line 5, in <module>
  File "D:\server\python34\lib\site-packages\jiracli\__init__.py", line 24, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'
D:\>python -V
Python 3.4.2
```

**Comment by tiger-seo** [comment] 2016-01-22 18:29
i guess the problem is because of python 3.4

**Comment by toabctl** [comment] 2016-01-23 07:05
Well - it's a problem. Let's reopen it.

**Comment by toabctl** [comment] 2016-01-23 07:15
Should be fixed with https://github.com/toabctl/jiracli/commit/988f99bd862097b0ff2a4deba1615265a5e093b8

**Comment by toabctl** [comment] 2016-01-23 07:16
Can you confirm? If so, I'll do a relase and upload it to pypi.

**Comment by toabctl** [comment] 2016-01-23 08:31
So I did the release now. Just test it with installing via pip (release version is 0.4.6). If the problem is still there, just repopen the bug. Thanks!

**Closed by toabctl** 2016-01-23 08:31 UTC
Labels: bug
